# Configuration parameters from the YAML-like file
import os
import random
import numpy as np
import pandas as pd
import torch
import torch.nn as nn

from torch import optim
from torch.nn import functional as F
from torch.utils.data import DataLoader
from torchvision import transforms
from tqdm import tqdm
import yaml

from mnist_dataset import CustomBinaryInsectDF
from vq_vae import VQVAE


class Discriminator(nn.Module):
    def __init__(self, in_channels=3, img_size=148):
        super(Discriminator, self).__init__()
        
        # Convolutional layers
        self.conv_layers = nn.Sequential(
            nn.Conv2d(in_channels, 32, kernel_size=3, stride=2, padding=1),
            nn.BatchNorm2d(32),
            nn.LeakyReLU(0.2),
            nn.Conv2d(32, 64, kernel_size=3, stride=2, padding=1),
            nn.BatchNorm2d(64),
            nn.LeakyReLU(0.2)
        )
        
        # Dynamically calculate the size of the feature map after conv layers
        # (Height and Width are halved at each stride-2 convolution)
        conv_output_height = img_size // (2 ** 2)  # 2 Conv layers
        conv_output_width = img_size // (2 ** 2)
        flattened_size = 64 * conv_output_height * conv_output_width
        
        # Fully connected layers
        self.fc_layers = nn.Sequential(
            nn.Flatten(),
            nn.Linear(flattened_size, 128),
            nn.BatchNorm1d(128),
            nn.LeakyReLU(0.2),
            nn.Dropout(0.3),
            nn.Linear(128, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        x = self.conv_layers(x)
        x = self.fc_layers(x)
        return x

def fetch_hard_negatives_batch(hard_neg_loader_iter, hard_neg_loader):
    try:
        return next(hard_neg_loader_iter)[0]
    except StopIteration:
        # Reinitialize the hard_neg_loader if exhausted
        hard_neg_loader_iter = iter(hard_neg_loader)
        return next(hard_neg_loader_iter)[0]
    

def train_discriminator(discriminator, discriminator_optimizer, model, images, device):
    """
    Trains the discriminator for one batch of images.

    Args:
        discriminator (nn.Module): The discriminator model.
        discriminator_optimizer (torch.optim.Optimizer): Optimizer for the discriminator.
        model (nn.Module): The VAE model (or any generator model).
        images (torch.Tensor): Batch of real images.
        device (torch.device): Device to run the computation (CPU or GPU).

    Returns:
        tuple: Total discriminator loss for the batch, real labels, and reconstructed images.
    """
    # Set discriminator to training mode
    discriminator.train()
    
    # Create real and fake labels
    real_labels = torch.ones((images.size(0), 1), device=device)
    fake_labels = torch.zeros((images.size(0), 1), device=device)
    
    # Train discriminator
    discriminator_optimizer.zero_grad()
    
    # Real images
    real_scores = discriminator(images)
    real_loss = F.binary_cross_entropy(real_scores, real_labels)
    
    # Fake images (generated by the model)
    recon_images, _, _ = model(images)
    fake_scores = discriminator(recon_images.detach())  # Detach to avoid backprop through the generator
    fake_loss = F.binary_cross_entropy(fake_scores, fake_labels)
    
    # Total loss
    disc_loss = real_loss + fake_loss
    disc_loss.backward()
    discriminator_optimizer.step()
    
    return disc_loss.item()


def train_adversarial_vae(model, discriminator, train_vae_loader, train_hard_negatives_loader, device, epochs, optimizer, discriminator_optimizer, \
              scheduler, discriminator_scheduler, patience, save_path_best):
    best_loss = float('inf')  # Initialize the best loss as infinity
    patience_counter = 0  # Counter for epochs without improvement

    # Initialize iterator for hard negatives
    train_hard_negatives_loader_iter = iter(train_hard_negatives_loader)

    for epoch in range(epochs):
        model.train()
        train_loss = 0.0
        train_recons_loss = 0.0
        train_vq_loss = 0.0
        total_disc_loss = 0.0
        hard_neg_loss = 0.0
        adv_fake_loss = 0.0

        for images, _, _, _, _, _ in tqdm(train_vae_loader, desc=f"Epoch {epoch+1}/{epochs}"):
            images = images.to(device)
            hard_neg_images = fetch_hard_negatives_batch(
                train_hard_negatives_loader_iter, 
                train_hard_negatives_loader
            )
            hard_neg_images = hard_neg_images.to(device)

            # Train discriminator
            total_disc_loss += train_discriminator(
                discriminator,
                discriminator_optimizer,
                model,
                images,
                device
            )

            # Forward pass
            recons, inputs, vq_loss = model(images)
            loss_dict = model.loss_function(recons, inputs, vq_loss)
            loss = loss_dict['loss']
            
            real_labels = torch.ones((images.size(0), 1), device=device)
            adv_fake_loss_ = F.binary_cross_entropy(discriminator(recons), real_labels)

            hard_neg_recons, _, _ = model(hard_neg_images)
            hard_neg_loss_ = F.mse_loss(hard_neg_recons, hard_neg_images, reduction='sum')

            total_loss = loss + adv_fake_loss_ - hard_neg_loss_

            # Backward pass
            optimizer.zero_grad()
            total_loss.backward()
            optimizer.step()

            train_loss += total_loss.item()
            train_recons_loss += loss_dict['Reconstruction_Loss'].item()
            train_vq_loss += loss_dict['VQ_Loss'].item()
            hard_neg_loss += hard_neg_loss_
            adv_fake_loss += adv_fake_loss_

        # Compute average losses for logging
        avg_train_loss = train_loss / len(train_vae_loader)
        avg_recons_loss = train_recons_loss / len(train_vae_loader)
        avg_vq_loss = train_vq_loss / len(train_vae_loader)
        avg_hard_neg_loss = hard_neg_loss / len(train_vae_loader)
        avg_adv_fake_loss = adv_fake_loss / len(train_vae_loader)

        print(f"Epoch [{epoch+1}/{epochs}] - Train Loss: {avg_train_loss:.4f}, "
            f"Reconstruction Loss: {avg_recons_loss:.4f}, VQ Loss: {avg_vq_loss:.4f}, "
            f"Hard Negatives Loss: {avg_hard_neg_loss:.4f}, Adv Fake Loss: {avg_adv_fake_loss:.4f}")

        # Check for improvement in training loss
        if avg_train_loss < best_loss:
            best_loss = avg_train_loss
            patience_counter = 0
            torch.save(model.state_dict(), save_path_best)  # Save the best model
            print(f"New best model saved at {save_path_best} with Train Loss: {best_loss:.4f}")
        else:
            patience_counter += 1
            print(f"No improvement. Patience counter: {patience_counter}/{patience}")
        
        # Step the scheduler
        scheduler.step()
        discriminator_scheduler.step()
        print(f"VAE Learning Rate: {scheduler.get_last_lr()[0]:.6f}, "
              f"Disc Learning Rate: {discriminator_scheduler.get_last_lr()[0]:.6f}")

        # Early stopping
        if patience_counter >= patience:
            print(f"Stopping early at epoch {epoch+1}. Best Train Loss: {best_loss:.4f}")
            break
    
    # Save the trained model
    torch.save(model.state_dict(), save_path)
    print(f"Model saved at {save_path}")


if __name__ == '__main__':
    # Load the configuration
    with open("config.yaml", "r") as file:
        config = yaml.safe_load(file)

    # Set manual seed for reproducibility
    torch.manual_seed(config["exp_params"]["manual_seed"])
    random.seed(config["exp_params"]["manual_seed"])
    np.random.seed(config["exp_params"]["manual_seed"])

    pin_memory = len(config['trainer_params']['gpus']) != 0

    df_test_path = os.path.join('data', f'df_test.csv')
    df_test = pd.read_csv(df_test_path)

    insect_classes = ['wmv', 'c']
    
    for i in range(len(insect_classes)):
        main_insect_class = insect_classes[i]
        mislabeled_insect_class = insect_classes[1 - i]

        df_train_vae_path = os.path.join('data', f'df_train_ae_{main_insect_class}.csv')
        df_train_vae = pd.read_csv(df_train_vae_path)

        df_train_hard_negatives_path = os.path.join('data', f'df_train_ae_{mislabeled_insect_class}.csv')
        df_train_hard_negatives_dirty = pd.read_csv(df_train_hard_negatives_path)
        df_train_hard_negatives = df_train_hard_negatives_dirty[df_train_hard_negatives_dirty.label==0]

        # Prepare Dataset
        transform = transforms.Compose([
            transforms.Resize((config["data_params"]["patch_size"], config["data_params"]["patch_size"])),
            transforms.ToTensor(),
            transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225))
        ])

        train_dataset_vae = CustomBinaryInsectDF(df_train_vae, transform = transform, seed=config["exp_params"]["manual_seed"])
        train_dataset_hard_negatives = CustomBinaryInsectDF(df_train_hard_negatives, transform = transform, seed=config["exp_params"]["manual_seed"])
        test_dataset_vae = CustomBinaryInsectDF(df_test, transform = transform, seed=config["exp_params"]["manual_seed"])

        train_vae_loader = DataLoader(
            train_dataset_vae, 
            batch_size=config["data_params"]["train_batch_size"], 
            shuffle=True,
            num_workers=config["data_params"]["num_workers"],
            pin_memory=pin_memory
        )
        train_hard_negatives_loader = DataLoader(
            train_dataset_hard_negatives, 
            batch_size=config["data_params"]["train_batch_size"], 
            shuffle=True,
            num_workers=config["data_params"]["num_workers"],
            pin_memory=pin_memory
        )
        test_loader = DataLoader(
            test_dataset_vae, 
            batch_size=config["data_params"]["train_batch_size"], 
            shuffle=False,
            num_workers=config["data_params"]["num_workers"],
            pin_memory=pin_memory
        )

        print(f"{main_insect_class} dataset correctly loaded")

        # Initialize the Model
        device = 'cuda' if torch.cuda.is_available() else 'cpu'

        model = VQVAE(
            in_channels=config["model_params"]["in_channels"],
            embedding_dim=config["model_params"]["embedding_dim"],
            num_embeddings=config["model_params"]["num_embeddings"],
            img_size=config["model_params"]["img_size"],
            beta=config["model_params"]["beta"]
        ).to(device)

        discriminator = Discriminator(in_channels=3, img_size=148).to(device)

        print(f"{main_insect_class} model correctly initialized")

        # Optimizer and Scheduler
        optimizer = optim.Adam(model.parameters(), lr=config["exp_params"]["LR"], weight_decay=config["exp_params"]["weight_decay"])
        scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer, gamma=config["exp_params"]["scheduler_gamma"])
        discriminator_optimizer = optim.Adam(discriminator.parameters(), lr=config["exp_params"]["LR"])
        discriminator_scheduler = torch.optim.lr_scheduler.ExponentialLR(discriminator_optimizer, gamma=config["exp_params"]["scheduler_gamma"])

        # Training Loop
        epochs = config["trainer_params"]["max_epochs"]
        patience = config["trainer_params"]["patience"]
        save_path = os.path.join(config["logging_params"]["save_dir"], f'{config["logging_params"]["name"]}_{main_insect_class}.pth')
        save_path_best = os.path.join(config["logging_params"]["save_dir"], f'{config["logging_params"]["name"]}_{main_insect_class}_best.pth')
        os.makedirs(config["logging_params"]["save_dir"], exist_ok=True)

        if not os.path.exists(save_path_best):
            print(f"{main_insect_class} start training")
            train_adversarial_vae(
                model,
                discriminator, 
                train_vae_loader,
                train_hard_negatives_loader, 
                device, 
                epochs, 
                optimizer,
                discriminator_optimizer, 
                scheduler, 
                discriminator_scheduler,
                patience, 
                save_path_best
            )
        else:
            print(f"{main_insect_class} loading best model")    
    print('')


