cleaning_params:
  adbench:
    outlier_detection_method: MCD
  adbench_2d:
    outlier_detection_method: PCA
  adbench_xd_hdbscan:
    outlier_detection_method: UmapHdbscanOD
  cnn:
    outlier_detection_method: UmapHdbscanOD
  cnn_corrected_mislabels:
    outlier_detection_method: UmapHdbscanOD
  cnn_no_od:
    outlier_detection_method: no_od
  strategies:
  - adbench
  - adbench_2d
  - adbench_xd_hdbscan
  - cnn
  - cnn_corrected_mislabels
  - cnn_no_od
  subsets:
  - train
  - val
data_params:
  batch_size: 64
  data_classes:
  - Pullover
  - Shirt
  file_extension: '*.png'
  image_size: 28
  nature_split:
  - 60
  - 20
  - 20
  num_workers: 0
  original_data_dir: data/fashionmnist
  raw_suffix: raw
  splitted_data_dir: data/split_60_20_20
  swap_suffix: swap
  trash_class: Bag
exp_params:
  LR: 0.0001
  manual_seed: 1
  weight_decay: 0.0
logging_params:
  save_dir: logs/
model_params:
  name: resnet18
  num_embeddings: 512
  pretrained: true
trainer_params:
  device: cuda:0
  gpus:
  - 1
  num_epochs: 25
  patience: 10
