data_params:
  batch_size: 64
  data_classes:
  - wmv
  - wrl
  nature_split:
  - 60
  - 20
  - 20
  num_workers: 0
  original_data_dir: data/phoneboxdata
  raw_suffix: raw
  splitted_data_dir: data/split_60_20_20
  swap_suffix: swap
  trash_class: not_insect
exp_params:
  LR: 1.0e-05
  manual_seed: 1
  weight_decay: 0.0
logging_params:
  save_dir: logs/
model_params:
  name: resnet18
  num_embeddings: 512
  pretrained: true
trainer_params:
  device: cuda:0
  gpus:
  - 1
  num_epochs: 25
  patience: 10
