data_params:
  data_path: Data/
  num_workers: 0
  patch_size: 148
  train_batch_size: 64
  val_batch_size: 64
exp_params:
  LR: 0.001
  kld_weight: 0.00025
  manual_seed: 1265
  scheduler_gamma: 0.98
  weight_decay: 0.0
logging_params:
  name: VQVAE
  save_dir: logs/
model_params:
  beta: 0.25
  embedding_dim: 64
  img_size: 148
  in_channels: 3
  name: VQVAE
  num_embeddings: 512
trainer_params:
  gpus:
  - 1
  max_epochs: 100
  patience: 10
